credentials:
  usernames:
    beatit:
      email: abessoloxavier45@gmail.com
      logged_in: False # Will be managed automatically
      name: Abessolo Ateba Abhas
      password: 'abc123' # Will be hashed automatically
cookie:
  expiry_days: 30
  key: cookie_signature_key # Must be string
  name: cookie_name
preauthorized:
  emails:
  - abessolo.ateba@azubiafrica.org
users: